services:
  db:
    image: postgres:15-alpine
    container_name: tds-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: semeadordb
      POSTGRES_USER: semeadoruser
      POSTGRES_PASSWORD: ${DB_PASSWORD:-semearv2_2025}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tds-network

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: tds-php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./uploads:/var/www/uploads
      - vendor_data:/var/www/html/vendor
    networks:
      - tds-network
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: tds-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - tds-network

volumes:
  pgdata:
  vendor_data:

networks:
  tds-network:
    driver: bridge